on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: intertechdemo.azurecr.io
        username: ${{ secrets.acr_intertechdemo_username }}
        password: ${{ secrets.acr_intertechdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t intertechdemo.azurecr.io/intertechdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push intertechdemo.azurecr.io/intertechdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_intertechdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: intertechdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_intertechdemo_username }}
        container-registry-password: ${{ secrets.acr_intertechdemo_password }}
        secret-name: intertechdemdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: helloworld
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:intertechdemo.azurecr.io/intertechdemo
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:intertechdemdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          intertechdemo.azurecr.io/intertechdemo:${{ github.sha }}
        imagepullsecrets: |
          intertechdemdockerauth
